name: simulator
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - orekit=11.0.2
    - numpy
    - czml3
    - matplotlib
    - pandas
    - nbformat
    - plotly
    - pip
    - pip:
        - pyquaternion
