"""
This type stub file was generated by pyright.
"""

def download_orekit_data_curdir(filename=...): # -> None:
    """
    Orekit needs a number of orientation and model parameters. An example file is available on the
    orekit gitlab. This funciton downloads that file to the current directory.

    Note that for non-testing purposes, this file should

    Args:
        filename (str): Store the downloaded data as this filename/path. Default is "orekit-data.zip"
    """
    ...

def setup_orekit_curdir(filename=...): # -> None:
    """Setup the java engine with orekit.

    This function loads the Orekit data from either:
        - A zip in the current directory (by default orekit-data.zip),
        - A folder,
    depending on whether `filename` is the path to a file or to a folder.

    Then the function sets up the Orekit DataProviders to access it.

    The JVM needs to be initiated prior to calling this function:

        orekit.initVM()

    Args:
        filename (str): Name of zip or folder with orekit data. Default filename is 'orekit-data.zip'


    """
    ...

def absolutedate_to_datetime(orekit_absolutedate): # -> datetime:
    """ Converts from orekit.AbsoluteDate objects
    to python datetime objects (utc)"""
    ...

def datetime_to_absolutedate(dt_date): # -> AbsoluteDate:
    """ Converts from python datetime objects (utc)
    to orekit.AbsoluteDate objects.

    Args:
        dt_date (datetime): python datetime object to convert

    Returns:
        AbsoluteDate: time in orekit format"""
    ...

def to_elevationmask(az, el): # -> ElevationMask:
    """ Converts an array of azimuths and elevations to a
    orekit ElevationMask object. All unts in degrees.

        mask = to_elevationmask([0, 90, 180, 270], [5,10,8,5])

    """
    ...

def JArray_double2D(x, y):
    """Returns an JCC wrapped 2D double array

    Args:
        x: Number of rows in the array
        y: Number of columns in the array

    Note that the rows and columns are returned as objects and
    are likely needed to be casted manually.
    """
    ...

